set number
set tabstop=4
set shiftwidth=4
set autoindent
set cursorline
set wildmenu
set noswapfile
set termguicolors
let ayucolor="dark"
syntax on

call plug#begin()
	Plug 'ayu-theme/ayu-vim'
call plug#end()

colorscheme ayu
